# Generated by Django 4.1.3 on 2022-12-08 10:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_yelp', models.CharField(default='', max_length=150)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('birthDate', models.DateField(default=datetime.date(2022, 12, 8), verbose_name='Date')),
                ('pseudo', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(default='img_user/avatar.jpeg', upload_to='img_user/')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('Debut_Horaire1', models.TimeField(default='00:00')),
                ('Fin_Horaire1', models.TimeField(default='00:00')),
                ('Debut_Horaire2', models.TimeField(default='00:00')),
                ('Fin_Horaire2', models.TimeField(default='00:00')),
                ('Debut_Horaire3', models.TimeField(default='00:00')),
                ('Fin_Horaire3', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRestaurant', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='liste_images')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_yelp', models.CharField(default='', max_length=150)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('ville', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(default='', max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('etat', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('note', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('image_front', models.ImageField(upload_to='img_restaurant/')),
                ('img', models.ManyToManyField(to='appsae.imagerestaurant')),
                ('type', models.ManyToManyField(to='appsae.restauranttype')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGroupe', models.IntegerField(default=0)),
                ('nom_groupe', models.CharField(max_length=25)),
                ('id_gerant', models.IntegerField(default=-1)),
                ('liste_adherants', models.ManyToManyField(to='appsae.adherant')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('texte', models.CharField(default=' ', max_length=1000)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 11, 12, 48, 230224))),
                ('unix_date', models.CharField(default='', max_length=1000)),
                ('adherant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.adherant')),
                ('restaurant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant')),
            ],
            options={
                'db_table': 'Avis',
            },
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('restaurant_fk', 'adherant_fk'), name='unique avis'),
        ),
    ]
