# Generated by Django 4.1.2 on 2022-11-10 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='note',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
