# Generated by Django 4.1.3 on 2022-12-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 11, 38, 39, 330833)),
        ),
    ]
