# Generated by Django 4.1.2 on 2022-10-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adhérant',
            new_name='Adherant',
        ),
        migrations.RenameField(
            model_name='groupe',
            old_name='nom',
            new_name='nom_groupe',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='liste_image',
        ),
        migrations.CreateModel(
            name='ImageRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/img/liste_images')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant')),
            ],
        ),
    ]
