# Generated by Django 4.1.2 on 2022-11-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0002_restaurant_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerestaurant',
            name='product',
        ),
        migrations.AddField(
            model_name='avis',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avis',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Debut_Horaire1',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Debut_Horaire2',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Debut_Horaire3',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Fin_Horaire1',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Fin_Horaire2',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='Fin_Horaire3',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.ManyToManyField(to='appsae.restauranttype'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='texte',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagerestaurant',
            name='image',
            field=models.ImageField(upload_to='liste_images'),
        ),
    ]
