# Generated by Django 4.1.3 on 2022-12-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0002_alter_avis_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 12, 27, 44, 94334)),
        ),
    ]
