# Generated by Django 4.1.2 on 2022-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0004_alter_restaurant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='etat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id_yelp',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ManyToManyField(to='appsae.imagerestaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
