# Generated by Django 4.1.3 on 2022-12-09 14:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0004_alter_avis_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherant',
            name='birthDate',
            field=models.DateField(default=datetime.date(2022, 12, 9), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 15, 2, 52, 407651)),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
