# Generated by Django 4.1.2 on 2022-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0005_alter_restaurant_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
    ]
