# Generated by Django 4.1.2 on 2022-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0005_restaurant_etat_restaurant_id_yelp_restaurant_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='img_restaurant/'),
        ),
    ]
