# Generated by Django 4.1.3 on 2022-12-09 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0006_alter_avis_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 15, 7, 34, 239376)),
        ),
    ]
