# Generated by Django 4.1.2 on 2022-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0006_restaurant_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherant',
            name='id',
        ),
        migrations.AlterField(
            model_name='adherant',
            name='mail',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
