# Generated by Django 4.1.2 on 2022-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0006_alter_restaurant_image_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
