# Generated by Django 4.1.2 on 2022-11-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0007_remove_adherant_id_alter_adherant_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
    ]
