# Generated by Django 4.1.2 on 2022-12-15 07:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0008_alter_avis_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='created_date',
        ),
        migrations.AddField(
            model_name='adherant',
            name='nb_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='birthDate',
            field=models.DateField(default=datetime.date(2022, 12, 15), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='unix_date',
            field=models.CharField(default=1671091177.299996, max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
