# Generated by Django 4.1.2 on 2022-11-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0008_alter_avis_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='user',
        ),
        migrations.AlterField(
            model_name='avis',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='appsae.restaurant'),
        ),
    ]
