# Generated by Django 4.1.2 on 2022-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0009_remove_avis_created_date_adherant_nb_review_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avis',
            name='unique avis',
        ),
        migrations.AlterField(
            model_name='avis',
            name='unix_date',
            field=models.CharField(default=1671091347.929674, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='avis',
            table=None,
        ),
    ]
