# Generated by Django 4.1.2 on 2022-11-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0009_remove_avis_user_alter_avis_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
    ]
