# Generated by Django 4.1.2 on 2022-11-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0010_alter_avis_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsae.adherant'),
        ),
    ]
