# Generated by Django 4.1.2 on 2022-11-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0012_rename_user_avis_adherant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='adherant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.adherant'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
    ]
