# Generated by Django 4.1.2 on 2022-11-22 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0013_alter_avis_adherant_alter_avis_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
