# Generated by Django 4.1.2 on 2022-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0014_alter_avis_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_front',
            field=models.ImageField(upload_to='img_restaurant/'),
        ),
    ]
