# Generated by Django 4.1.2 on 2022-11-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0015_alter_restaurant_image_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerestaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='imagerestaurant',
            name='idRestaurant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagerestaurant',
            name='default',
            field=models.BooleanField(blank=True),
        ),
    ]
