# Generated by Django 4.1.3 on 2022-11-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0007_remove_adherant_id_alter_adherant_mail'),
        ('appsae', '0016_remove_imagerestaurant_name_and_more'),
    ]

    operations = [
    ]
