# Generated by Django 4.1.3 on 2022-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0018_alter_restaurant_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerestaurant',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
