# Generated by Django 4.1.3 on 2022-11-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0019_alter_imagerestaurant_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='adherant',
            new_name='adherant_fk',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='restaurant',
            new_name='restaurant_fk',
        ),
    ]
