# Generated by Django 4.1.3 on 2022-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0020_rename_adherant_avis_adherant_fk_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('restaurant_fk', 'adherant_fk'), name='unique avis'),
        ),
        migrations.AlterModelTable(
            name='avis',
            table='Avis',
        ),
    ]
