# Generated by Django 4.1.3 on 2022-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0021_avis_unique avis_alter_avis_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='idGroupe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupe',
            name='liste_adherants',
            field=models.ManyToManyField(to='appsae.adherant'),
        ),
    ]
