# Generated by Django 4.1.2 on 2022-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0022_groupe_idgroupe_groupe_liste_adherants'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherant',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupe',
            name='id_gerant',
            field=models.IntegerField(default=-1),
        ),
    ]
