# Generated by Django 4.1.2 on 2022-12-09 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0023_adherant_id_groupe_id_gerant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
