# Generated by Django 4.1.3 on 2022-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0023_adherant_id_groupe_id_gerant'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='time_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='avis',
            name='adherant_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsae.adherant'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='restaurant_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
    ]
