# Generated by Django 4.1.2 on 2022-12-11 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0024_alter_avis_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
