# Generated by Django 4.1.3 on 2022-12-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0024_avis_time_created_alter_avis_adherant_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='time_created',
        ),
        migrations.AlterField(
            model_name='avis',
            name='adherant_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.adherant'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='restaurant_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsae.restaurant'),
        ),
    ]
